### ISSUE TITLE
Behavior while syncing

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#100]
@antonlerner [pointed out](https://github.com/spacemeshos/go-spacemesh/pull/2071/files#r456897616) that some API services shouldn't be available until the node is synced. I'm not sure this is realistic from a product perspective, @avive what do you think? However, until the node is synced, some data will be missing so some API calls as implemented now will return errors, see e.g. several of the endpoints in MeshService. What should we do if the user asks the API for data the node hasn't synced yet? Some options:

1. Don't enable the MeshService or GlobalStateService at all until the node is synced
1. Don't enable certain endpoints until the node is synced
1. Return an "internal error"
1. Return an "invalid input" error

Related: #50

**Comment by lrettig** [comment]
To be clear, this is more about getting an internal understanding about expected API behavior, and should be documented/enforced in various implementations, but I don't expect this to result in changes to rpc methods.

**Comment by avive** [comment]
I think that we should go with option #1 above. Originally, we wanted clients such as explore to sync a backing node from genesis and update storage with new layers data via the streams but since then we've added methods for historical data that at least an archive node will be able to fully satisfy.  I re-checked the current api definitions and it should be possible to get all historical data once synced for clients such as explorer at least for mesh data following this pattern: 1. get a layer. 2. query for tx state and receipts for all txs in the mesh in that layer. 2. subscribe to future layers via the streams. Regarding global state, I think we are missing a method to get older global state root hashes but it is not very useful until we have the strong consensus via the validators node on global state.

**Comment by avive** [comment]
I also think that the tx service should be disabled for now until fully synced.

**Comment by lrettig** [comment]
@avive to be clear, this means that, if the mesh contains many layers and it takes hours or days to fully sync the mesh from scratch, a new node won't be able to allow _any_ API queries whatsoever until it's fully synced. On a slow/spotty internet connection, this might mean those API services never become available. It sounds like a pretty bad client experience to me. Are you sure it wouldn't make more sense to enable these services and allow them to return data for old layers that are fully synced, while the sync is still in progress? (This corresponds to options 3. and 4. above.)

**Comment by avive** [comment]
Ideally we'll be able to have these operational while syncing from a user experience, but we are not talking about any api query - we only talk about 3 services that are not going to be available until being synced.... it will be much nicer if the streaming apis are operational and output data while sync is happening so clients ui can update with the new data but the balance will keep changing for a wallet account so this is a negative...

**Comment by avive** [comment]
Full node clients can't rely on balance data and list of transactions until their node is synced anyhow. They can get partial data as the node sync but the try current values can only be obtained when synced... so maybe it is better not to show bad data at all until we know that the data is good... Slow sync is an inherent problem of the architecture - we are not going to fix this usability problem by showing partial data as the node synced - at least not for account balance and list of account transactions...

**Comment by lrettig** [comment]
It might not make sense to show historical state data, as you point out, but there's no reason you wouldn't want to see historical mesh data as it becomes available

**Comment by lrettig** [comment]
The behavior of the current implementation is that all API services can be started at any time, including when the node is not in sync. If a client requests data that the node does not know about yet, they'll get an error, probably `InvalidInput`. The burden is on the client to know whether the node is in sync, and what layer it is synchronized/state has been applied up to. This is trivial using the node status endpoint.

One exception is SubmitTransaction, which should return an error if the node is not in sync - submitting data is different since, if the node were to accept the tx, it would not be able to broadcast it anyway and it would remain in the mempool, which is an error. This is being addressed in https://github.com/spacemeshos/go-spacemesh/issues/2103.

I'm happy with the way this works now, so I'm going to close this issue. I'll make sure the behavior is documented. If you still disagree, reopen and we can continue discussing.
