### ISSUE TITLE
Transaction receipts

### ISSUE THREAD

**Issue by avive** [spacemeshos/api#11]
To know the results of a transaction, something which is important for a user who owns an account involved in this transaction, the full node will need to store all transaction receipts since genesis as these hold the result of execution of the transaction while the raw transactions in the mesh do not have this info. Wallets want to fetch all the transactions for an account - these are in the mesh but also all the receipts so it can display the execution result of the transaction. 
This is an issue to bring up for discussion.

**Comment by avive** [comment]
Yes, to recap we said full node will only store receipts and events n layers from current time and archive node is exactly the same but stores everything. We have a bit more work on the spec of archive node in terms of api to ask for state of app or account in any layer....

**Comment by lrettig** [comment]
Full node vs. archive node is probably beyond the scope of this issue. Going to close this one. Thanks!
