### ISSUE TITLE
Add support for network friendly name 

### ISSUE THREAD

**Issue by avive** [spacemeshos/api#116]
It will be nice to have a friendly network name and the network config file and the api to return it to clients.
This will enable display of the friendly name in dash and explore without further clients config.
For example, we want the header of the dash of this net to say `Devnet 17` instead of `17` and we want to display something like `TweedleDee 118` for open testnet dash / explore so TweedleDee will be the friendly network name in the config file.

https://stage-dash.spacemesh.io/

**Comment by lrettig** [comment]
> It will be nice to have a friendly network name and the network config file and the api to return it to clients.

You mean add a friendly network name into the existing config file?

My gut feeling is that this is a bad idea, and that it's something we should probably let clients do on their own - one good reason is localization and languages. I think a client can contain a mapping from network ID to (local, friendly) name. We could maintain a public database of these if necessary, e.g.: https://chainid.network/.

**Comment by avive** [comment]
I guess we can add it to dash and explore back-ends.
