### ISSUE TITLE
'epochnum' endpoint returns an empty result when in epoch 0

### ISSUE THREAD

**Issue by AmitShaul** [spacemeshos/api#137]
'epochnum' endpoint returns an empty result when in epoch 0

result = {'epochnum': {}}
wanted result = {'epochnum': {'value': 0}}

**Comment by avive** [comment]
This also affects explore and dash on net id 126. This is a new issue due to recent api changes. See https://explorer-126.spacemesh.io/epochs - missing epoch 0. @lrettig

**Comment by lrettig** [comment]
This is a duplicate of #87. It's an artifact of the grpc design and we cannot change it. Default values are always empty, and zero is the default value for an integer.

**Comment by avive** [comment]
Shouldn't GRPC clients just handle this gracefully?

**Comment by lrettig** [comment]
> Shouldn't GRPC clients just handle this gracefully?

Yes. The only alternative here is to change the type of epochnum, layernum, etc. so it's not an int, and I don't think we want to do that.
