### ISSUE TITLE
Mesh transaction api error

### ISSUE THREAD

**Issue by avive** [spacemeshos/api#142]
1. Submit a transaction to your local node from a client and note your account address.
2. Call MeshService.AccountMeshDataQuery(account_address, <transaction_flag>) to get all transactions for that account.

Result: api returns `rpc error: code = Internal desc = error retrieving tx data`
Expected: return all mesh transactions and no error.

Now wait few minutes and try again - you'll get no error. 
Hypothesis: there must be some internal state where the transaction is not yet in the mem pool or in a block where the transaction causes an error in the node.

**Comment by avive** [comment]
This likely should go into go-sm repo as it is an implementation error.

**Comment by avive** [comment]
I'll move this to go-sm repo

**Comment by lrettig** [comment]
https://github.com/spacemeshos/go-spacemesh/issues/2372
