### ISSUE TITLE
Support increasing and decreasing PoST size via API endpoints

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#15]
Per https://github.com/spacemeshos/SMIPS/issues/6

**Comment by avive** [comment]
It should be fully supported in the latest release but may not be that obvious.

**Comment by avive** [comment]
yes. To change the post data, just call it with a different commitment size at the same path.

**Comment by lrettig** [comment]
I made this clearer in the comment, thanks. Closing.
