### ISSUE TITLE
Add layer information for transactions in MeshService

### ISSUE THREAD

**Issue by avive** [spacemeshos/api#153]
# Motivation
We have a deficiency in the current api design where MeshService doesn't provide clients with the mesh layer that transactions are in. Clients need this information for: 1. order transactions in display. 2. display tx status based on tx layer and current node's notion of verified layer. e.g. `Pending` / `Confirmed`. Both are basic tx information that users of the platform will expect to be able to see. 

Note that having the tx receipt api implemented (it is currently not implemented) would not have fully resolved this issue as clients wants the above data for txs that haven't yet been executed by the STF and receipts are only generated by STF execution.

We need to solve this issue to provide a minimally usable experience for smapp 0.2 clients such as smrepl and smapp.

# Proposed solution

There are 2 main proposed solutions to address this issues for 0.2 based on the above new api type:

1. A fully backward compatible solution: Add `AccountMeshDataQueryEx` and `AccountMeshDataStreamEx` to return `AccountMeshDataEx`.

```proto
message MeshTransaction {
    Transaction transaction = 1;
    LayerNumber layernum = 2;
}

message AccountMeshDataEx {
    oneof datum {
        MeshTransaction mesh_transaction = 1;
        Activation activation = 2;
    }
}
```

2. Update AccountMeshData:

```proto
message AccountMeshData {
    oneof datum {
        MeshTransaction mesh_transaction = 1;
        Activation activation = 2;
    }
}

message MeshTransaction {
    Transaction transaction = 1;
    LayerNumber layernum = 2;
}
```

I recommend we adopt the 2nd solution as the fix for the current main client - explorer backend should be quite straightforward to apply, and long-term the api remains cleaner and simpler to use this way without ant hackish `extended` methods. Also note that the second solution makes the api more consistent because `Activation` already includes the layer number.

**Comment by dshulyak** [comment]
I went with the 2nd approach. We are probably not at the point when backward compatibility is mandatory.

**Comment by avive** [comment]
> I went with the 2nd approach. We are probably not at the point when backward compatibility is mandatory.

There's a good change this will break the explorer backend process so we need to open an issue there to alert about a breaking change so it can be updated.

**Comment by lrettig** [comment]
IIRC, in our original API design, we explicitly did not include layer or block context in transactions since transactions exist independently of the mesh itself: e.g., when they're gossiped, or in the mempool. The design is that, if you want to know which layer a tx was included in, you need the receipt:

https://github.com/spacemeshos/api/blob/105249951c66561cfc52195433ecae9cd5a121ff/proto/spacemesh/v1/global_state_types.proto#L66

**Comment by avive** [comment]
> IIRC, in our original API design, we explicitly did not include layer or block context in transactions since transactions exist independently of the mesh itself: e.g., when they're gossiped, or in the mempool. The design is that, if you want to know which layer a tx was included in, you need the receipt:
> 
> https://github.com/spacemeshos/api/blob/105249951c66561cfc52195433ecae9cd5a121ff/proto/spacemesh/v1/global_state_types.proto#L66

I also comments on the other related issues:
1. We need to ship a usable Smapp and Smrepl 0.2 and I'm not aware that implementing receipts is going to happen in 0.2 - the only way that the user experience regarding transaction is going to be minimally usable is if we at least have layer number of transactions that the user cares about - so I don't see any other alternative to provide this besides introducing the MeshTransaction type.
2. The overall design pattern doesn't need to change - I was not proposing to change the Transaction data type - just add a new notion of MeshTransaction that has that additional info and it makes sense conceptually because a MeshTransaction _has _a layer id.
3. What you note above does not entirely cover all cases at all times regarding the data that the user cares about regarding a tx - there's a time period between the time a transaction is on the mesh until the STF runs and produces a receipt. In this time period the node knows that the tx is on the mesh in a layer and it should def report it to clients so they can present this status to users.

**Comment by dshulyak** [comment]
I assume that we agreed that the proposed solution is fine, and I can go ahead with merging PRs?
I created an issue in https://github.com/spacemeshos/explorer-backend/issues/10 . It appears that this endpoint in that application.

**Comment by avive** [comment]
@lrettig - how do we proceed on resolving this?

**Comment by lrettig** [comment]
Closing per comment in https://github.com/spacemeshos/api/pull/155#issuecomment-881015398
