### ISSUE TITLE
ATX model missing fields

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#27]
From [Slack standup](https://spacemesh.slack.com/archives/CREMHKGT0/p1590669101025700) today:

Alina Tustanovska: 4. [ATXs]: Wold you like us to add ActiveSetSize param to Transaction, or even better to define ATX as a separate type and add the ATXs field to the Block?

Alina Tustanovska:
type ActivationTxHeader struct {
 NIPSTChallenge
 id      *ATXID // non-exported cache of the ATXID
 Coinbase   Address
 ActiveSetSize uint32
}
type NIPSTChallenge struct {
 NodeID        NodeID
 Sequence       uint64
 PrevATXID      ATXID
 PubLayerID      LayerID
 StartTick      uint64
 EndTick       uint64
 PositioningATX    ATXID
 CommitmentMerkleRoot []byte
}

i.e., this is part of the ATX struct in go-spacemesh but isn't currently captured by the API.

CC @primaveralina

**Comment by avive** [comment]
Few notes:
1. We need to get feedback from Anton or Noam on these as there are ATX changes as part of the protocol changes.
2. We need to generalize transaction type to support both ATXs and smart contract transactions soon anyhow.
3. For now, it is fine to assume ATX transaction type. For that transaction as far as I can tell the only interesting data items for explore/dash are:

- Prev ATX ID - Valid previous ATX (I think that currently myst be in prev epoch but may change soon)
- Commitment size (of the proof which is part of the atx) - e.g. 100GB.
- Coinbase address - the rewards address provided by the smesher with this atx/
- Smesher id - The ID of the smesher who published this at.

**Comment by avive** [comment]
I dob't think that the other fields mentioned in this issue which I didn't list in my comment are useful for dash/explore or wallet. We also want to get feedback from @noamnelke on this topic.

**Comment by noamnelke** [comment]
This area is currently in flux. I’m removing the active set size entirely and replacing with total epoch weight.

In parallel, Anton is moving the declaration from the ATX to the first transaction from a miner in each epoch.

It isn’t great to build on these things while they change, but 🤷🏻‍♂️

**Comment by avive** [comment]
> It isn’t great to build on these things while they change, but 🤷🏻‍♂️

Yes, this is why we ignore them for now and only add the fields are mention above which I think are not going to change with the new atx construction.
