### ISSUE TITLE
Rename "Commitment"

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#39]
Tal takes offense at our choice of the word "Commitment" (since it has a specific, cryptographic meaning elsewhere in our protocol). Let's rename the types/messages to PostData, AllocatedData, or something else - maybe DiskSpaceAllocatedToSpacemesh? :)

**Comment by avive** [comment]
DiskSpaceAllocatedToSpacemesh is way too long. I would just use PostData.

**Comment by lrettig** [comment]
> DiskSpaceAllocatedToSpacemesh is way too long. I would just use PostData.

I like descriptive variable names 🤷‍♂️
