### ISSUE TITLE
Missing app state root hash in TransactionReceipt

### ISSUE THREAD

**Issue by avive** [spacemeshos/api#41]
We should have a bytes filed with the app storage root hash in an app execution transaction.

**Comment by avive** [comment]
@YaronWittenstein - we also need you to review the Transaction and TransactionReceipt data structures and make sure they include all the svm related information.

**Comment by lrettig** [comment]
What's the purpose here? Also cf. #34 where we propose adding a state delta as well

**Comment by avive** [comment]
I think these are 2 different things. For a smart contract tx, we need to output in the receipt the state of the app storage after the execution. Maybe even the hash of the state just prior to it (possibly after the previous txs in the same layer that got the state to where it is. The most basic thing. We need to do this regardless if we do what is discussed in the other issue.

**Comment by lrettig** [comment]
> For a smart contract tx, we need to output in the receipt the state of the app storage after the execution

Why do we need this?

**Comment by lrettig** [comment]
I don't see why we need this on a per-tx basis. We'll have it on a per-layer basis. As I've said [over and over again](https://github.com/spacemeshos/api/issues/36#issuecomment-640069034), the STF is not well-defined over a single tx (due to the way we handle rewards) so I'm not even sure this is technically possible. I'm going to close this, but @avive @yaronwittenstein feel free to try to convince me otherwise.

**Comment by YaronWittenstein** [comment]
To my understanding, the `App State` Hash can be derived per-tx. 

I know that in practice, the STF will derive the rewards after executing the block transactions and do only a one-time flush to disk, but the `App State` value should not be affected by that.

**Comment by lrettig** [comment]
Thanks @YaronWittenstein. Do you feel that the API needs to include this?

**Comment by YaronWittenstein** [comment]
API needs of the `STF` component should be able to loop over the layer-transactions,
execute each transaction and in the end, ask for all the dirty changes from the Global State and have a one `flush` call
(and of course, also take for the rewards)

**Comment by lrettig** [comment]
@YaronWittenstein I'm a bit confused - what do you mean by

> The API of the STF component

? I guess you're referring to the GlobalStateService? The service is "dumb" - it contains no logic about executing transactions, getting dirty changes, etc. It can only read things from the database.

Where and when does this process you're describing happen inside go-spacemesh? Are you suggesting that when SVM executes a tx, it does this, and we add the app state root to the tx object in the database?
