### ISSUE TITLE
What should Build return?

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#58]
Clarify exactly what we want here: branch, tag, or commit? Intuitively, to me, commit seems more useful than branch.

Also, we might want to rename this endpoint to be clearer about this.

@avive ?

https://github.com/spacemeshos/api/blob/f3755c611ab3372b38e9deb4fbf83a7c1df21903/proto/spacemesh/v1/node.proto#L21-L22

**Comment by avive** [comment]
We want the node version which is what is printed today in the first log line which can be equal to a release tag but is more flexible as it can be set to something else plus the commit hash. I think that both are included today in the node.

**Comment by lrettig** [comment]
The clearest thing to do here, IMHO, is to return the git commit hash as the build. I'll do that, and I've updated the description of this endpoint to make it clearer. Let me know if you disagree for any reason.
