### ISSUE TITLE
Set log level endpoint

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#59]
go-spacemesh currently has a set log level endpoint (`SetLoggerLevel`). I don't think we have one of these in the API right now. Do we want one? @avive ?

**Comment by avive** [comment]
yes, it will be very useful for testing.

**Comment by lrettig** [comment]
> However, we do want to have a log level for api request handling by the node. Logging the complete request and response params if the level is set to debug should be good.

If I'm understanding you correctly, this sounds orthogonal to the API itself - i.e., this is implementation-specific and would be specified in, e.g., the go-spacemesh config like we do now per-module, right?

**Comment by lrettig** [comment]
I think this can be accomplished using the config file as Aviv mentioned. I'm going to remove this functionality from go-spacemesh entirely for reasons I described in https://github.com/spacemeshos/go-spacemesh/issues/2090, and I'm not planning to add it to the new API. Speak now or forever hold your peace.

CC @ilyavi @ilans
