### ISSUE TITLE
Design user control over api facades

### ISSUE THREAD

**Issue by avive** [spacemeshos/api#6]
We need to figure out how to enable node users to enable and disable specific api facades independently via GRPC. We need to research what is the best way to do this. We are likely not the first ones who came across this problem. Ideally we'll be able to do this while still having 1 GRPC endpoint tied to a specific port.

**Comment by lrettig** [comment]
It's definitely possible to attach multiple grpc services to a single server instance. Here's one example in golang: https://stackoverflow.com/questions/52634217/access-multiple-grpc-services-over-the-same-connection/52635877.

Therefore I propose that we implement each facade as a separate service, and selectively turn the services on and off using commandline flags.

Good?

**Comment by avive** [comment]
yes. So we have a solution to dynamically enable or disable services which is what we needed.

**Comment by lrettig** [comment]
![hi-five](https://media2.giphy.com/media/WS4hut8lsqe38lF5lI/giphy.gif)

**Comment by lrettig** [comment]
The work will be done in go-spacemesh. Closing in favor of spacemehsos/go-spacemesh#1983.
