### ISSUE TITLE
Get transactions endpoint

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#60]
go-spacemesh has one today, but the API does not. Right now the API just returns tx receipts, which include a txid. CC @avive

**Comment by avive** [comment]
I think it should be part of the node service and return a transaction if the node knows about it. This should include transactions that the node submitted or got from the mempool and transactions which are on the mesh. If we put this in the mesh service then it doesn't make sense to return a transaction that the node knows about which is not yet on the mesh.

**Comment by avive** [comment]
We have a transactions service. I think we should just modify TransactionsState() to include the transaction object in the TransactionsStateResponse. This makes sense as it will return to the caller the tx data (immutable) and its current state (mutable).

**Comment by avive** [comment]
We might also want to add a flag to the param if the caller wants the full tx data (tx object) in the response or not because there will be many cases where it already has it and just want to know what the current state is.
