### ISSUE TITLE
Wallet usage patterns

### ISSUE THREAD

**Issue by avive** [spacemeshos/api#7]
Thinking further on API2 for wallet-type clients.

A wallet needs data from genesis for specific entities, for example - all transactions to/from an account. There are 2 main ways to design this:
1. Have pull method with pagination support. e.g. `MeshGetAccountTranscations(AccountId, offset) returns (TransactionsList)`. Wallet will call this for a specific account with offset 0 initially - get the results and continue to pull until it got all the results it needs.

2. Specify a start layer number in a stream of transactions and receive a stream of transactions since that layer. e.g. `MeshStreamAccountTransactions(AccountId, LayerNumber) returns (stream Transaction). Call this with layernumber = 0 to get a stream of results since genesis... keep listening on this server-side data stream for new applicable transactions.

**Comment by lrettig** [comment]
These aren't mutually exclusive. I see no reason not to have both, a paginated endpoint and a stream endpoint.

It's not clear what happens in case 1. if there's a reorg. If the consumer keeps asking for page after page, it might be oblivious to the fact that the reorg happened. We might solve this by adding statefulness and some sort of "session ID" to consecutive requests for multiple pages, but that's messy for other reasons. Case 1. obviously also misses things like status changes to a previous tx, which is where the stream is useful.

One caveat on 2., as discussed a stream can only return _new_ data, not historical data, so I'm not sure it makes sense to pass in a start layer number as you proposed.

**Comment by avive** [comment]
I think we addressed this with the latest version of the api and we agreed on the usage patterns. Is there anything else to do on this issue?

**Comment by lrettig** [comment]
Nope, I think we're good. Does the documentation at https://github.com/spacemeshos/api#queries-and-streams match your understanding? I intend to improve the documentation a bit more as part of #67 

I'm going to assume we're good here and close this, feel free to reopen if necessary
