### ISSUE TITLE
Submit binary transaction endpoint

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#78]
We don't currently have one of these. The `TxService.SubmitTransaction` endpoint accepts a `Transaction` type which is structured and does not contain binary data (aside from the signature):

https://github.com/spacemeshos/api/blob/279f08c40938d979697559aa88bec16c8aab6ff8/proto/spacemesh/v1/types.proto#L105-L116

Per https://github.com/spacemeshos/SMIPS/issues/23 it looks like we need an endpoint to receive signed, binary tx data. Note that the existing, old API does contain an endpoint that does this (`SubmitTransaction`).

CC @avive

**Comment by avive** [comment]
I think that this is just an oversight on our part that we should correct. `TxService.SubmitTransactio()` should accept a byte[] and clients are expected to pass an XDR encoded transaction which includes the signature. Clients need to generate this blob based on the transactions syntax spec  - similar to how Smapp and CLIwallet do this today.

**Comment by avive** [comment]
We will need to update all transactions related api methods to support the new sm tx format - this is part of the reason I'm pushing for a spec via the smip asap.
