### ISSUE TITLE
Same tx in multiple layers?

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#8]
As discussed [in Slack today](https://spacemesh.slack.com/archives/C89QJJY3G/p1588256607286400), it appears that a tx can hypothetically be included in two different layers. This could cause issues for downstream data consumers, e.g., in an explorer a tx could have two receipts, one success (the first one) and one failure (second one, when once is wrong).

**Comment by avive** [comment]
And also in this case the transaction will appear on the mesh on 2 different layers. It was my understanding that a transaction can appear in more than 1 block in a layer but not in 2 different layers of the mesh. We need to clarify this.

**Comment by lrettig** [comment]
Cf. https://github.com/spacemeshos/api/pull/2#discussion_r417523517
