### ISSUE TITLE
layer number data type

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#88]
It appears to be uint32 in some places, uint64 in others. Let's pick one and standardize.

https://github.com/spacemeshos/api/blob/a91231e795693339a4bda4ea1b70df4b25d8919d/proto/spacemesh/v1/mesh_types.proto#L89-L90

https://github.com/spacemeshos/api/blob/a91231e795693339a4bda4ea1b70df4b25d8919d/proto/spacemesh/v1/types.proto#L115

CC @avive

**Comment by avive** [comment]
I think we should standardize around uint32.

**Comment by lrettig** [comment]
So actually in go-spacemesh it's uint64:

https://github.com/spacemeshos/go-spacemesh/blob/61eafeeb2a9e3ec785113cf8284eec8bf8ef6ee9/common/types/block.go#L38

Agree that we should standardize - should we just use uint64? Do we want to loop research into this thread?

**Comment by avive** [comment]
@noamnelke - any reason why layer number shouldn't be uint32 in the api and maybe even in go-spacemesh soon? I think that with 5 minutes layers we are talking about 41,425 years of mesh represented in 32 bits.

**Comment by noamnelke** [comment]
You know what a pain it will be to upgrade the protocol in 41k years??

I'm obviously kidding and I don’t think we need research on this, but... it sounds like a messy task.

@lrettig you want to only apply this to the api or go-spacemesh as well?

**Comment by noamnelke** [comment]
Just noticed the “good first issue” label 👌🏻

**Comment by lrettig** [comment]
@noamnelke I'll work on both
