### ISSUE TITLE
Tortoise, Hare, and LayerStatus

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#89]
Right now in the API design layers have three possible statuses:

https://github.com/spacemeshos/api/blob/a91231e795693339a4bda4ea1b70df4b25d8919d/proto/spacemesh/v1/types.proto#L116-L120

However, this does not map cleanly to how things are implemented in go-spacemesh. In reality, a layer may be in any of the following (mutually exclusive) states:

- brand new, hasn't passed tortoise or hare, not yet applied to state
- passed hare, applied to state, hasn't passed tortoise yet
- passed hare, applied to state, passed tortoise (in this case, whether or not pbase advanced doesn't matter since it was applied to state when it passed hare)
- skipped hare entirely, passed tortoise, and applied to state (pbase advanced) (while syncing)
- skipped hare entirely, passed tortoise, not yet applied to state yet (pbase hasn't advanced) (while syncing)

I don't know how to map these "real" statuses to the ones in the API. Do we need to add more?

CC @avive, thank you @antonlerner for helping me figure this out

**Comment by lrettig** [comment]
@avive how do you want to handle this? We need to make a call here for the API implementation (https://github.com/spacemeshos/go-spacemesh/pull/2059)

**Comment by avive** [comment]
We have to decouple the state and STF execution from this. Here, we only care about the consensus on the layer and not the application of state of txs in this layer. If you disregard state for this api then it maps pretty cleanly.
Of-course we need to thing about self healing where I think hare and tortoise may run again on one or more layers but I'm not 100% sure about that.

**Comment by lrettig** [comment]
> If you disregard state for this api then it maps pretty cleanly

Even disregarding state, we still have:

- brand new, hasn't passed tortoise or hare, not yet applied to state
- passed hare, hasn't passed tortoise yet
- passed hare, passed tortoise
- skipped hare entirely, passed tortoise (while syncing)
skipped hare entirely, passed tortoise, not yet applied to state yet (pbase hasn't advanced) (while syncing)

These clearly don't map to three statuses. We either need to add a fourth, or we need to make "passed tortoise" and "passed hare" orthogonal.

**Comment by avive** [comment]
So I think this will be good:

- brand new, hasn't passed tortoise or hare, not yet applied to state => 0
- passed hare, hasn't passed tortoise yet => 1
- passed hare, passed tortoise => 2
- skipped hare entirely, passed tortoise (while syncing) => 2

Unless there's some special meaning to a layer which passed both hare and tortoise. I think that what we care about is the level of certainty which is expressed in approved / confirmed... So, if a layer was confirmed we don't care it was approved or not as it doesn't add any degree of consensus on it. But maybe I'm wrong @tal-m ?

**Comment by lrettig** [comment]
This has been implemented:

https://github.com/spacemeshos/go-spacemesh/blob/cf406036a2c6311fb2093dde768d1caf8ee3059f/api/grpcserver/mesh_service.go#L352-L362
