### ISSUE TITLE
Lay out milestones for API

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#9]
@avive what do you think?

- 0.1: barebones API we planned for explorer/dashboard
- 0.2: adds endpoints for smapp
- 0.3: adds stuff related to VM

**Comment by avive** [comment]
I would go with these as the current api is 1.0 in the node...
1.1 - barebones api for dash / explore - I think this is right now in the 0.2 branch - correct?
1.2 - api 1.1 + all the method the app needs excluding smart contracts ones (to some extent as there are overlaps).
1.3 - api 1.2 + all smart contract related capabilities.

**Comment by lrettig** [comment]
> 1.1 - barebones api for dash / explore - I think this is right now in the 0.2 branch - correct?

This is 0.1 (in the branch you originally opened, `initial-feedback`, since reviewed and merged into master). I cut an 0.1 release for this already.

> 1.2 - api 1.1 + all the method the app needs excluding smart contracts ones (to some extent as there are overlaps).
> 1.3 - api 1.2 + all smart contract related capabilities.

Sounds right, modulo the 0.2/0.3 vs. 1.2/1.3 difference,

**Comment by avive** [comment]
ok so `smeshing-methods` should be `0.3` and there should be a `0.1` branch not 2 - correct?

**Comment by avive** [comment]
Since what we have in the current node is already labelled v1.0 and what is now `0.1` is a major revamp of that - I think 0.1 should be v2.0 and the other branches v2.x - minor versions over 2.0. I don't see a reason above to why you oppose this. It will be very awkward to move from api 1.0 to api 0.1...

**Comment by lrettig** [comment]
> It will be very awkward to move from api 1.0 to api 0.1...

Where is the API versioned today?

**Comment by lrettig** [comment]
> ok so `smeshing-methods` should be `0.3` and there should be a `0.1` branch not 2 - correct?

Yes, `smeshing-methods` is 0.3. It sort of subsumes the work we did for 0.2 so I am inclined to just combine these two.

**Comment by avive** [comment]
yes - let's combine

**Comment by lrettig** [comment]
Nothing more to do here
