### ISSUE TITLE
Stateless vs. stateful NodeStatusStream

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#92]
The `NodeStatus` returns info on several aspects of the status of a running node, and the `NodeStatusStream` returns a stream of these. However, the running node does not produce these status objects atomically: different services in the node report different status items at different times.

https://github.com/spacemeshos/api/blob/ff4a9a6b913a23a83cf07a0a7b4b7c16605ce9c0/proto/spacemesh/v1/node_types.proto#L36-L42

Do we want the status reported by a node to be _stateful_ or _stateless?_ Stateful would mean that the reporting infrastructure saves a snapshot of the most recent status, and just updates whatever was most recently reported - e.g., the start of a new layer - and returns the entire status snapshot. Stateless would mean that we just report whatever we know, when we know it - e.g., the new current layer - with no other information.

Note that, if we go the stateful route, we may also want to include a timestamp with each status item so we know how recent they are, in case, e.g., one gets quite out of date.

CC @avive

**Comment by avive** [comment]
I think it needs be stateful to be useful. Stateless direction applies separating these into different event. I think that it makes sense to leave this aggregated but there might be a way to implement this without storing any values internally. For example, say there's a new layer (time passed), at this point the impl knows it needs to send a status update to clients, it can pull the other current data from the different components, e.g. is_synced, sycned_layer, etc... internally each component knows the current value of this data. I think this is quite close to how the /v1/status api works today. I think it is too granular to have an event when each of these grouped data item changed. Makes sense?

**Comment by lrettig** [comment]
How important do you think it is that a status message pulls in all of the
latest status data, as you describe? Versus just showing whatever was last
reported. Certain things, such as IsSynced, get reported very often --
every few seconds -- and polling everything that often would create a
higher burden on the node in resources, as well as making the code more
complex. I'm inclined to just store a single Status object, update whatever
new info is received in the normal fashion, then send that over the wire.

I think there's a deeper question here about how recent we expect these
data to be, and how often they should be updated.

Do you think we should include a timestamp for each data item so we know
how recent it is?

>

**Comment by avive** [comment]
I guess you can do that as well. A message should be sent every time one of the data items value is changed. I don't think we need a timestamp - it is a bit of an overkill. I think that storing a status object and updating it each time one of its member gets updated and sending it to clients on the stream is just fine.

**Comment by lrettig** [comment]
I ended up simplifying this a lot. There's not really any need to keep state here: as you suggested, the NodeService just needs to know when something has changed, then it can fetch the changed data on its own. Change is here: https://github.com/spacemeshos/go-spacemesh/pull/2071/commits/d4d76b6eaf550f7732a10e208ceb7001d0b34664.
