### ISSUE TITLE
Change NodeErrorType enum to match ordinary debug levels

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/api#93]
I'm struggling to map these to the error types in go-spacemesh. I propose that, instead of this relatively arbitrary set of error types, we instead map these to the ordinary set of error levels: debug, info, warn, error, panic, etc.

https://github.com/spacemeshos/api/blob/ff4a9a6b913a23a83cf07a0a7b4b7c16605ce9c0/proto/spacemesh/v1/node_types.proto#L58-L65

@avive where did this list come from? Can we change it?

**Comment by lrettig** [comment]
Also, SIGNAL_SHUT_DOWN seems a bit out of place here - where did this come from?

**Comment by avive** [comment]
The idea is to fire an event when node is shutting down w/o polling - it is important for wallets such as smapp so it doesn't have to keep pinging the local node to check it is alive. I don't think we have it anywhere else. It is not technically an error but if we remove it from here then we should add a stream where clients can get notified when the node is shutting down...

**Comment by lrettig** [comment]
Okay. Any other thoughts on the different error types here? Are you okay if
we switch to using the ordinary log levels?

>

**Comment by lrettig** [comment]
See attached PR - I changed error "type" to level to match the levels defined here: https://github.com/uber-go/zap/blob/53a387079b46cce51bbb6d360d9c57f86977addb/level.go#L28-L47

We can add a separate "type" enum if necessary

**Comment by avive** [comment]
Why do you want to change to error levels? This type need to specify a specific runtime error and not an error level.

**Comment by lrettig** [comment]
We discussed this and agreed to split this up into three pieces:

- level, which matches the log level as described above (https://github.com/spacemeshos/api/issues/93#issuecomment-663749207). Note that we currently only transmit errors >= ERROR level (i.e., we do not transmit debug, info, warn, etc.), and that ERROR should be considered recoverable, whereas the PANIC and FATAL levels should be considered irrecoverable errors - although I cannot guarantee that the levels are always used correctly in go-spacemesh.
- module, i.e., the component/protocol that generated the error (its source): could be hare, sync, mesh, etc.
- error text, i.e., a description of what went wrong

I'll update #102 accordingly
